// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqxkhdwqyypnmrfhzggj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxeGtoZHdxeXlwbm1yZmh6Z2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDk5MzgsImV4cCI6MjA1ODQ4NTkzOH0.TpryBHLIaWJa1elULp8yd-lgOAv1EjvoGSx72k9u_Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);